version: '3'
services:
  rdflib-endpoint:
    container_name: openpredict-sparql-service
    build: .
    restart: unless-stopped
    environment: 
      VIRTUAL_HOST: service.openpredict.137.120.31.102.nip.io
      LETSENCRYPT_HOST: service.openpredict.137.120.31.102.nip.io
      VIRTUAL_PORT: 80
    # ports:
    #   - 8000:80

